[package]
name = "http"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
actix-web = "4.13.0"
anyhow = "1.0.102"
bitcask-rs = { workspace = true }
quote = "1.0.44"
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { version = "0.1.44", features = ["log"] }
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
